# Generated by Django 5.2.17 on 2026-09-04 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('annonce', 'Annonce publiée'), ('candidature', 'Adhésion'), ('inscription', 'Inscription événement'), ('rappel', 'Rappel J-1 / H-2h'), ('convocation', 'Convocation / rappel H-48h'), ('satisfaction', 'Retour post-activité'), ('recap', 'Récap hebdomadaire'), ('promotion', 'Promotion liste d’attente')], max_length=14)),
                ('titre', models.CharField(max_length=140)),
                ('message', models.TextField(blank=True)),
                ('destinataire_email', models.EmailField(blank=True, max_length=254)),
                ('objet_id', models.CharField(blank=True, max_length=40, verbose_name='Id objet lié (événement, candidature…)')),
                ('envoye', models.BooleanField(default=True, verbose_name='Email parti (False = log-only / prefs / erreur)')),
                ('resend_id', models.CharField(blank=True, max_length=40, verbose_name='Id Resend')),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
