# Generated by Django 5.2.17 on 2026-09-04 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'objet_id'], name='notificatio_type_d62fc3_idx'),
        ),
    ]
