# Generated by Django 5.2.17 on 2026-09-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(choices=[('P1', 'Président'), ('P2', 'Vice-Présidente'), ('P3', 'Secrétaire Générale'), ('P4', 'Responsable des Cellules'), ('P5', 'Responsable Communication'), ('P6', 'Responsable des Activités'), ('P7', 'Resp. Innovation & Solutions'), ('P8', 'Coordinateur des Opportunités'), ('P9', 'Resp. Programmation'), ('P10', 'Responsable des Ateliers'), ('CHEF_CELLULE', 'Chef de cellule'), ('MEMBRE', 'Membre'), ('ADMIN', 'Administrateur')], max_length=20, verbose_name='Poste')),
                ('mission', models.TextField(verbose_name='Mission')),
                ('objectif', models.TextField(verbose_name='Objectif prioritaire')),
            ],
            options={
                'unique_together': {('role_code',)},
            },
        ),
    ]
