# Generated by Django 5.2.17 on 2026-09-04 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_points'),
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('type', models.CharField(choices=[('hackathon', 'Hackathon'), ('conference', 'Conférence'), ('partenariat', 'Partenariat')], default='hackathon', max_length=12)),
                ('statut', models.CharField(choices=[('veille', 'En veille'), ('interesse', 'Intéressé'), ('inscrit', 'Inscrit'), ('cloture', 'Clôturé')], default='veille', max_length=10)),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('lien', models.URLField(blank=True, verbose_name='Lien externe')),
                ('contact_nom', models.CharField(blank=True, max_length=120, verbose_name='Contact (nom)')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact (email)')),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_limite', '-maj_le'],
            },
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('cle', models.SlugField(max_length=60, primary_key=True, serialize=False, verbose_name='Clé')),
                ('valeur', models.TextField(blank=True, verbose_name='Valeur')),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('idee', 'Idée'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='idee', max_length=10)),
                ('lien', models.URLField(blank=True, verbose_name='Lien (repo, démo…)')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('cellule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='accounts.cellule')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_diriges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-maj_le'],
            },
        ),
    ]
