# Generated by Django 5.2.17 on 2026-09-04 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_opportunite_parametre_projet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('reunion_date', models.DateField(verbose_name='Date de la réunion')),
                ('lieu', models.CharField(blank=True, max_length=140)),
                ('ordre_du_jour', models.TextField(blank=True, verbose_name='Ordre du jour')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_validation', 'En validation'), ('publie', 'Publié')], default='brouillon', max_length=14)),
                ('publie_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crs_rediges', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crs_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reunion_date', '-maj_le'],
            },
        ),
    ]
