# Generated by Django 5.2.17 on 2026-09-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_compterendu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourceVeille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lien', models.URLField(verbose_name='Lien')),
                ('theme', models.CharField(choices=[('ia', 'IA & Data'), ('web', 'Web & Mobile'), ('cyber', 'Cybersécurité'), ('cloud', 'Cloud & DevOps'), ('autre', 'Autre')], default='autre', max_length=12)),
                ('resume', models.TextField(blank=True, max_length=600, verbose_name='Résumé')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('partage_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veilles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='VoteVeille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_veille', to=settings.AUTH_USER_MODEL)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.ressourceveille')),
            ],
        ),
        migrations.AddIndex(
            model_name='ressourceveille',
            index=models.Index(fields=['theme'], name='governance__theme_380752_idx'),
        ),
        migrations.AddIndex(
            model_name='voteveille',
            index=models.Index(fields=['ressource'], name='governance__ressour_f93676_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voteveille',
            unique_together={('ressource', 'membre')},
        ),
    ]
