# Generated by Django 5.2.17 on 2026-09-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_ressourceveille_voteveille_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compterendu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comptes-rendus/', verbose_name='Photo du rapport'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='video_url',
            field=models.URLField(blank=True, help_text='Coller le lien de la vidéo — les fichiers lourds ne passent pas par le serveur.', max_length=500, verbose_name='Lien vidéo (YouTube, Drive…)'),
        ),
    ]
