# Generated by Django 5.2.17 on 2026-09-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_compterendu_image_compterendu_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projets/', verbose_name='Visuel du projet'),
        ),
    ]
