# Generated by Django 5.2.17 on 2026-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_projet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compterendu',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='comptes-rendus/', verbose_name='Photo du rapport'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='projets/', verbose_name='Visuel du projet'),
        ),
    ]
