# Generated by Django 5.2.17 on 2026-09-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_alter_compterendu_image_alter_projet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='opportunites/', verbose_name='Visuel (affiche, capture…)'),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='video_url',
            field=models.URLField(blank=True, help_text='Coller le lien — les fichiers lourds ne passent pas par le serveur.', max_length=500, verbose_name='Lien vidéo (présentation…)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='video_url',
            field=models.URLField(blank=True, help_text='Coller le lien — les fichiers lourds ne passent pas par le serveur.', max_length=500, verbose_name='Lien vidéo (démo, pitch…)'),
        ),
    ]
