# Generated by Django 5.2.17 on 2026-09-09 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cellule_image'),
        ('governance', '0008_opportunite_image_opportunite_video_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('detail', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('examinee', 'À létude'), ('adoptee', 'Adoptée'), ('refusee', 'Non retenue')], default='proposee', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to=settings.AUTH_USER_MODEL)),
                ('cellule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='accounts.cellule')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
