# Generated by Django 5.2.17 on 2026-09-03 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('atelier', 'Atelier'), ('competition', 'Compétition'), ('conference', 'Conférence'), ('sortie', 'Sortie')], default='atelier', max_length=12)),
                ('couleur', models.CharField(default='#2563EB', max_length=9)),
                ('date_debut', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=140)),
                ('places', models.PositiveIntegerField(default=0, verbose_name='Places (0 = illimité)')),
                ('icone', models.CharField(default='ampoule', max_length=30, verbose_name='Id icône front')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_attente', models.BooleanField(default=False)),
                ('confirme', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evenement', 'membre')},
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='inscrits',
            field=models.ManyToManyField(blank=True, related_name='evenements_inscrits', through='events.Inscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
