# Generated by Django 5.2.17 on 2026-09-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin (satisfaction envoyée 1h après)'),
        ),
    ]
