# Generated by Django 5.2.17 on 2026-09-04 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_evenement_date_fin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['date_debut'], name='events_even_date_de_54bf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['evenement', 'liste_attente'], name='events_insc_eveneme_d071e8_idx'),
        ),
    ]
