# Generated by Django 5.2.17 on 2026-09-04 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_evenement_events_even_date_de_54bf5b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='code_presence',
            field=models.CharField(blank=True, default='', help_text='Généré automatiquement ; affiché au vidéoprojecteur le jour J.', max_length=6, verbose_name='Code de présence (6 chiffres, feuille émargement doc 02 D5)'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque_le', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='events.evenement')),
                ('marque_par', models.ForeignKey(blank=True, help_text='Orga ayant émargé (null = auto via code).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['evenement'], name='events_pres_eveneme_5a6220_idx')],
                'unique_together': {('evenement', 'membre')},
            },
        ),
    ]
