# Generated by Django 5.2.17 on 2026-09-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_evenement_code_presence_presence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Bilan')),
                ('points_forts', models.TextField(blank=True, verbose_name='Points forts')),
                ('points_ameliorer', models.TextField(blank=True, verbose_name='À améliorer')),
                ('publie', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='events.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(verbose_name='Note 1-5')),
                ('avis', models.TextField(blank=True, max_length=1000, verbose_name='Avis libre')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='events.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['evenement'], name='events_reto_eveneme_1a25ad_idx')],
                'unique_together': {('evenement', 'membre')},
            },
        ),
    ]
