# Generated by Django 5.2.17 on 2026-09-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_bilan_retour'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name="Affiche de l'activité"),
        ),
        migrations.AddField(
            model_name='evenement',
            name='video_url',
            field=models.URLField(blank=True, help_text='Coller le lien — les fichiers lourds ne passent pas par le serveur.', max_length=500, verbose_name='Lien vidéo (teaser, replay…)'),
        ),
    ]
