# Generated by Django 5.2.17 on 2026-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_evenement_image_evenement_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='evenements/', verbose_name="Affiche de l'activité"),
        ),
    ]
