# Generated by Django 5.2.17 on 2026-09-03 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('famille', models.CharField(choices=[('fondamentaux', 'Fondamentaux'), ('vie', 'Vie du club'), ('archives', 'Archives')], default='fondamentaux', max_length=14)),
                ('couleur', models.CharField(default='#1FAF72', max_length=9)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('extrait', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('date', models.DateField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tag_cellule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to='accounts.cellule')),
            ],
            options={
                'verbose_name_plural': 'actualites',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('legende', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], default='photo', max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='galerie/')),
                ('youtube_id', models.CharField(blank=True, max_length=24, verbose_name='ID YouTube')),
                ('evenement', models.CharField(blank=True, max_length=80, verbose_name='Événement (filtre)')),
                ('icone', models.CharField(default='trophee', max_length=30, verbose_name='Id icône front')),
                ('date', models.DateField(auto_now_add=True)),
                ('tag_cellule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cellule')),
            ],
            options={
                'verbose_name_plural': 'médias',
                'ordering': ['-date'],
            },
        ),
    ]
