# Generated by Django 5.2.17 on 2026-09-04 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=1000)),
                ('masque', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='comms.actualite')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='comms.commentaire')),
            ],
            options={
                'ordering': ['cree_le'],
                'indexes': [models.Index(fields=['actualite', 'masque'], name='comms_comme_actuali_b6ad28_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=8)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comms.actualite')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['actualite'], name='comms_react_actuali_d64209_idx')],
                'unique_together': {('actualite', 'membre', 'emoji')},
            },
        ),
    ]
