# Generated by Django 5.2.17 on 2026-09-04 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_points'),
        ('comms', '0002_commentaire_reaction'),
        ('governance', '0002_opportunite_parametre_projet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espace', models.CharField(choices=[('general', 'Général'), ('cellule', 'Cellule'), ('projet', 'Projet')], default='general', max_length=10)),
                ('titre', models.CharField(max_length=140)),
                ('epingle', models.BooleanField(default=False)),
                ('verrouille', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets_forum', to=settings.AUTH_USER_MODEL)),
                ('cellule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='accounts.cellule')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='governance.projet')),
            ],
            options={
                'ordering': ['-epingle', '-derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='MessageForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=2000)),
                ('modere', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_forum', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='comms.sujet')),
            ],
            options={
                'ordering': ['cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='sujet',
            index=models.Index(fields=['espace', 'cellule', 'projet'], name='comms_sujet_espace_c7b499_idx'),
        ),
        migrations.AddIndex(
            model_name='messageforum',
            index=models.Index(fields=['sujet', 'modere'], name='comms_messa_sujet_i_4faa76_idx'),
        ),
    ]
