# Generated by Django 5.2.17 on 2026-09-04 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_points'),
        ('comms', '0003_sujet_messageforum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('choix_multiple', models.BooleanField(default=False)),
                ('clos', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sondages', to=settings.AUTH_USER_MODEL)),
                ('cellule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sondages', to='accounts.cellule')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='OptionSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=120)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='comms.sondage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_sondages', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comms.optionsondage')),
            ],
        ),
        migrations.AddIndex(
            model_name='sondage',
            index=models.Index(fields=['cellule'], name='comms_sonda_cellule_f5323d_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['option'], name='comms_vote_option__f0804d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('option', 'membre')},
        ),
    ]
