# Generated by Django 5.2.17 on 2026-09-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_sondage_optionsondage_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='video_url',
            field=models.URLField(blank=True, help_text='Coller le lien — les fichiers lourds ne passent pas par le serveur.', max_length=500, verbose_name='Lien vidéo (reportage, interview…)'),
        ),
    ]
