# Generated by Django 5.2.17 on 2026-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0005_actualite_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='actualites/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(max_length=500, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='galerie/'),
        ),
    ]
