# Generated by Django 5.2.17 on 2026-09-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_alter_actualite_image_alter_document_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='espace',
            field=models.CharField(choices=[('general', 'Général'), ('cellule', 'Cellule'), ('projet', 'Projet'), ('bureau', 'Bureau (privé)')], default='general', max_length=10),
        ),
    ]
