# Generated by Django 5.2.17 on 2026-09-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0007_alter_sujet_espace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Lien ou ID YouTube'),
        ),
    ]
