# Generated by Django 5.2.17 on 2026-09-03 23:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/membres/', verbose_name='Photo')),
                ('promotion', models.CharField(blank=True, max_length=20, verbose_name='Promotion')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('programme', models.JSONField(default=list, verbose_name='Programme')),
                ('couleur', models.CharField(default='#1FAF72', max_length=9, verbose_name='Couleur charte')),
                ('couleur_fonce', models.CharField(default='#0E7A50', max_length=9, verbose_name='Couleur texte (WCAG)')),
                ('icone', models.CharField(default='web', max_length=30, verbose_name='Id icône front')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre d’affichage')),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cellules_dirigees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'cellules',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField(default=dict, verbose_name='Réponses du formulaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=12)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_traitees', to=settings.AUTH_USER_MODEL)),
                ('cellules_souhaitees', models.ManyToManyField(blank=True, to='accounts.cellule')),
            ],
            options={
                'verbose_name': 'candidature',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('P1', 'Président'), ('P2', 'Vice-Présidente'), ('P3', 'Secrétaire Générale'), ('P4', 'Responsable des Cellules'), ('P5', 'Responsable Communication'), ('P6', 'Responsable des Activités'), ('P7', 'Resp. Innovation & Solutions'), ('P8', 'Coordinateur des Opportunités'), ('P9', 'Resp. Programmation'), ('P10', 'Responsable des Ateliers'), ('CHEF_CELLULE', 'Chef de cellule'), ('MEMBRE', 'Membre'), ('ADMIN', 'Administrateur')], max_length=20, unique=True, verbose_name='Code')),
                ('interim', models.BooleanField(default=False, verbose_name='Intérim (VP)')),
                ('depuis', models.DateField(blank=True, null=True, verbose_name='En poste depuis')),
                ('titulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MembreCellule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depuis', models.DateField(auto_now_add=True)),
                ('cellule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='accounts.cellule')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cellule', 'membre')},
            },
        ),
    ]
