# Generated by Django 5.2.17 on 2026-09-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_prefs',
            field=models.JSONField(blank=True, default=dict, help_text='{"rappel": true, "recap": false…} — absent = accepté.', verbose_name='Préférences notifications (doc 02 D10)'),
        ),
    ]
