# Generated by Django 5.2.17 on 2026-09-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notif_prefs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['statut'], name='accounts_ca_statut_94cc3a_idx'),
        ),
    ]
