# Generated by Django 5.2.17 on 2026-09-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidature_accounts_ca_statut_94cc3a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points de participation (gamification)'),
        ),
    ]
