# Generated by Django 5.2.17 on 2026-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bootstrap_acces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='photos/membres/', verbose_name='Photo'),
        ),
    ]
