# Generated by Django 5.2.17 on 2026-09-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='cellules/', verbose_name='Visuel de la cellule'),
        ),
    ]
